set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mode-keys vi
set -g history-limit 100000
set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g mouse on
set -sg escape-time 0
set -g clock-mode-style 24
set -g default-terminal "tmux-256color"

set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

EF_BG="#2d3c34"
EF_BG2="#3d484d"
EF_FG="#d3c6aa"
EF_GREEN="#a7c080"
EF_AQUA="#83c092"
EF_YELLOW="#dbbc7f"
EF_GRAY="#859289"

set -g status-style                 "bg=$EF_BG,fg=$EF_FG"
set -g status-left-length           40
set -g status-right-length          80
set -g status-left                  "#[bg=$EF_GREEN,fg=$EF_BG,bold] #S #[bg=$EF_BG,fg=$EF_GREEN]"
set -g status-right                 "#[fg=$EF_GRAY] %H:%M  %d %b #[bg=$EF_GREEN,fg=$EF_BG,bold] #h "
set -g window-status-format         " #I:#W "
set -g window-status-current-format "#[bg=$EF_BG2,fg=$EF_AQUA,bold] #I:#W "
set -g pane-border-style            "fg=$EF_BG2"
set -g pane-active-border-style     "fg=$EF_GREEN"
set -g message-style                "bg=$EF_BG2,fg=$EF_YELLOW"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key -T copy-mode-vi v   send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y   send-keys -X copy-selection-and-cancel

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
bind c new-window -c "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm'
